dict = {
    'ww': 129,
    'www': 45,
    'w ww': 20,
    'w bw': 12,
    'w bb': 3,
    'w www': 10,
    'w bww': 10,
    'w bbw': 4,
    'w bbb': 2,
    'b ww': 8,
    'b bw': 4,
    'b bb': 2,
    'b www': 3,
    'b bww': 4,
    'b bbw': 2,
    'b bbb': 2,
    'ww w': 23,
    'ww b': 8,
    'ww ww': 25,
    'ww bw': 17,
    'ww bb': 5,
    'ww www': 11,
    'ww bww': 12,
    'ww bbw': 5,
    'ww bbb': 3,
    'bw w': 12,
    'bw b': 4,
    'bw ww': 14,
    'bw bw': 8,
    'bw bb': 3,
    'bw www': 6,
    'bw bww': 4,
    'bw bbw': 4,
    'bw bbb': 2,
    'bb w': 2,
    'bb b': 2,
    'bb ww': 1,
    'bb bw': 4,
    'bb bb': 2,
    'bb bww': 1,
    'bb bbw': 4,
    'bb bbb': 1,
    'www ww': 8,
    'www bw': 8,
    'www bb': 4,
    'www www': 4,
    'www bww': 6,
    'www bbw': 4,
    'www bbb': 3,

    'bbw ww': 2,
    'bbw bw': 4,
    'bbw bb': 2,
    'bbw www': 1,
    'bbw bww': 2,
    'bbw bbw': 1,
    'bbw bbb': 2,
    'bbb bb': 4,
    'bbb bbw': 2,
    'bbb bbb': 2,
}

scores = ['bbbb', 'bbww', 'bwww', 'wwww', 'bbb', 'bbw', 'bww', 'www', 'bb', 'bw', 'ww', 'b', 'w', '']